### ISSUE TITLE
The index creation for collections should change to FAISS

### ISSUE THREAD

**Issue by bigben80** [aws-samples/amazon-bedrock-samples#130]
hi, 

According to the [bedrock knowledge base document website](https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-setup.html), now the vector index should choose "faiss" as engine. 

If still use the "nmslib" engine as written in the [sample code](https://github.com/aws-samples/amazon-bedrock-samples/blob/main/agents/create-agent-and-kb/cdk-deployment/assets/lambda-function-create-kb/create_knowledge_base.py), user will get error like this:

_[ERROR] ValidationException: An error occurred (ValidationException) when calling the CreateKnowledgeBase operation: The knowledge base storage configuration provided is invalid... The OpenSearch Serverless engine type associated with your vector index is invalid. Recreate your vector index with one of the following valid engine types: FAISS. Then retry your request._

**Comment by bs258q** [comment]
`err=ValidationException('An error occurred (ValidationException) when calling the CreateKnowledgeBase operation: The knowledge base storage configuration provided is invalid... The OpenSearch Serverless engine type associated with your vector index is invalid. Recreate your vector index with one of the following valid engine types: FAISS. Then retry your request.'), type(err)=<class 'botocore.errorfactory.ValidationException'>`

I have faced the same error and as per knowledge base index ;
"engine": "nmslib", has to be changed to "engine": "faiss", please make this change ASAP

**Comment by mani-aiml** [comment]
Closing this issue, as it has been fixed.
