### ISSUE TITLE
Custom model import - Llama 3 8B sample: Wrong torch_type in PEFT model

### ISSUE THREAD

**Issue by lopezfelipe** [aws-samples/amazon-bedrock-samples#193]
Hello -- The [sample](https://github.com/aws-samples/amazon-bedrock-samples/blob/main/custom_models/import_models/llama-3/llama3-sftt-llama3-fine-tuning.ipynb) for importing a custom model into Bedrock has a bug when loading the PEFT model.

The current script will finish training but will result in a model that Bedrock cannot load.
```
# load PEFT model
model = AutoPeftModelForCausalLM.from_pretrained(
    training_args.output_dir,
    low_cpu_mem_usage=True,
    torch_dtype=torch_dtype
)
```
The issue appears to be fixed when changing the `torch_dtype` definition to `torch.float16`

**Comment by rsgrewal-aws** [comment]
fixed
