### ISSUE TITLE
error deploying `bedrock-agent-cdk` example

### ISSUE THREAD

**Issue by jritsema** [aws-samples/amazon-bedrock-samples#40]
I got the following error when following the instructions in [bedrock-agent-cdk](https://github.com/aws-samples/amazon-bedrock-samples/tree/main/agents/bedrock-agent-cdk#how-to-run). /cc: @rppth 

```
cdk bootstrap
/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/bedrock-agent-cdk.ts:3:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

3 import * as path from 'path';
                        ~~~~~~
bin/bedrock-agent-cdk.ts:4:23 - error TS2307: Cannot find module 'glob' or its corresponding type declarations.

4 import * as glob from 'glob';
                        ~~~~~~
bin/bedrock-agent-cdk.ts:5:22 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

5 import * as cdk from 'aws-cdk-lib';
                       ~~~~~~~~~~~~~

    at createTSError (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jritsema/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2307, 2307, 2307 ]
}
```

Here are my dependencies
```
cdk --version
2.113.0 (build ccd534a)

node --version
v18.17.1

npm --version
9.6.7
```

**Comment by maxtybar** [comment]
Hi @jritsema, could you run `npm install` before `cdk bootstrap` from within the same root directory (`bedrock-agent-cdk`)?  We will update this in the README. Thank you.

**Comment by maxtybar** [comment]
I have update the README so you can find more information about that. There is also no need for aws-lambda-python-alpha construct and no need for Docker. And you shouldn't need to add anything extra. Please make sure you copied the lates updated repository and you face the same issue run ``npm install --force``. Let me know if that helps.

**Comment by jritsema** [comment]
Great!  Seems to be working now.  Thanks @maxtybar!

**Comment by jritsema** [comment]
One other question @maxtybar.  Where is the intended place to iterate on the agent instruction?  Is it [here](https://github.com/aws-samples/amazon-bedrock-samples/blob/main/agents/bedrock-agent-cdk/lib/assets/lambdas/cdk-resource-bedrock-agent.py#L69)?  Might be nice to maintain at the [top level](https://github.com/aws-samples/amazon-bedrock-samples/blob/main/agents/bedrock-agent-cdk/bin/bedrock-agent-cdk.ts) as it is as key differentiated piece of info that lives alongside the schema and the implementation.

**Comment by maxtybar** [comment]
@jritsema Yes, you are correct, it is inside `cdk-resource-bedrock-agent.py` file. I actually did not intend to expose this because it was meant to serve just as an example of how you could deploy your agent and later be able to edit your agent's information (such as instruction, alias, version, etc.) in the AWS console. We have more robust, though not as customizable, agent deployment samples (such as [this](https://github.com/aws-samples/amazon-bedrock-samples/tree/main/agents/create-agent-only)). Also, feel free to explore a full AWS CDK Construct [here](https://constructs.dev/packages/bedrock-agents-cdk/v/0.0.6?lang=typescript) that has a better agent implementation that you could incorporate in your AWS CDK code. In the meantime, thank you for the feedback and I will incorporate it in the update!
