### ISSUE TITLE
In https://github.com/aws-samples/amazon-bedrock-samples/blob/main/agents/agentsforbedrock-retailagent/README.md, please include the text of the "Instructions for the Agent" 

### ISSUE THREAD

**Issue by mirodrr** [aws-samples/amazon-bedrock-samples#55]
Currently, the instructions are only in this image:
![image](https://github.com/aws-samples/amazon-bedrock-samples/assets/113373534/66b1bbce-f712-4598-b9ca-e8ef3896d85d)

This forces anyone who uses your sample to type the instructions manually

**Comment by mirodrr** [comment]
I just typed it out myself, so here it is just in case you no longer have it:

You are an agent that helps customers purchase shoes. Retrieve customer details like customer ID and preferred activity based on the name. Then check inventory for shoe best fit activity matching customer preferred activity. Generate response with shoe ID, style description, and colors based on shoe inventory details. If multiple matches exist, display all of the to the user. After customer indicates they would like to order the shoe, use the shoe ID corresponding to their choice and customer ID from initial customer details retrieved, to place order for the shoe.

**Comment by mttanke** [comment]
agents examples have been refactored, not applicable anymore
