### ISSUE TITLE
In https://github.com/aws-samples/amazon-bedrock-samples/tree/main/agents/insurance-agent-sendreminders, it is not specified whether "user input" should be set to "yes" or "no" 

### ISSUE THREAD

**Issue by mirodrr** [aws-samples/amazon-bedrock-samples#56]
In https://github.com/aws-samples/amazon-bedrock-samples/tree/main/agents/insurance-agent-sendreminders, it is not specified whether "user input" should be set to "yes" or "no" 

I suggest adding screenshots of exactly what should be done in the console UI, similar to what is done for the "agentsforbedrock-retailagent" sample here: https://github.com/aws-samples/amazon-bedrock-samples/tree/main/agents/agentsforbedrock-retailagent

**Comment by mttanke** [comment]
agents examples have been refactored, not applicable anymore
