### ISSUE TITLE
retail agent

### ISSUE THREAD

**Issue by orossant** [aws-samples/amazon-bedrock-samples#99]
When you ask the agent you want shoes, he ask your name.
If your name is not present in the database, the agent will not be able to manage this edge case.

Root cause : 
- csbot_lambfa_function doesn't manage empty result
![Pasted image 20240225120628](https://github.com/aws-samples/amazon-bedrock-samples/assets/11798129/ac3da5ee-cd0e-4480-9b81-7812c0dd653d)

**Comment by mttanke** [comment]
agents examples have been refactored, not relevant anymore
